### ISSUE TITLE
Running into issue with cloning this repository

### ISSUE THREAD

**Issue by aliforgetti** [jmportilla/Python-for-Algorithms--Data-Structures--and-Interviews#24]
![image](https://user-images.githubusercontent.com/17579534/105643354-fa07a180-5e54-11eb-8b9a-f13b49ff14b4.png)

**Comment by tushar098** [comment]
facing the exact same issue

**Comment by HurryNair** [comment]
+1

**Comment by sharpk1** [comment]
Try the following and please let me know if it works:
1. `git lfs install`
2. `git config --system core.longpaths true`
3. `GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/jmportilla/Python-for-Algorithms--Data-Structures--and-Interviews.git`

I went HAM on this and somehow ended up with the files: 
![image](https://user-images.githubusercontent.com/32557637/109581250-9c085280-7ac1-11eb-9924-b65d0a6e7efd.png)



These threads helped along the way: [thread 1](https://github.com/mozilla/webcompat-ml-docs/issues/1) [thread 2](https://stackoverflow.com/questions/39542177/warning-clone-succeeded-but-checkout-failed)

**Comment by sudoneoox** [comment]
+1

**Comment by tushar098** [comment]
Working.
Thanks a lot.

**Comment by damtur** [comment]
I've created a PR to address this issue: https://github.com/jmportilla/Python-for-Algorithms--Data-Structures--and-Interviews/pull/26

**Comment by jmportilla** [comment]
We've reorganized and reformated the notebooks and folder structure

**Comment by VivekWisdom** [comment]
This is still a problem.
